# Generated by Django 5.2.3 on 2026-06-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/%Y/%m/%d/"),
        ),
    ]
