# Generated by Django 5.2.3 on 2026-05-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="name",
        ),
    ]
