# Generated by Django 5.2.3 on 2026-05-10 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
    ]
