# Generated by Django 5.2.3 on 2026-05-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_review_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="rating",
            new_name="ratings",
        ),
    ]
