# Generated by Django 5.2.3 on 2026-05-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_rename_rating_review_ratings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="description",
            new_name="comment",
        ),
    ]
