# Generated by Django 5.2.3 on 2026-05-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_review_created_at_review_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
